### PR TITLE
Fix aiohttp AttributeError

### LINKED ISSUE #6: AttributeError: module 'aiohttp' has no attribute 'Timeout'
I'm currently testing this library with the Python >= 3.5.1 example from the README. Yet when running that exact same code with only the app_id, api_key, index_name and search terms replaced I get this error:

```
algoliasearch.helpers.AlgoliaException: ('Unreachable hosts: %s', {'<APP_ID>-dsn.algolia.net': "AttributeError: module 'aiohttp' has no attribute 'Timeout'", '<APP_ID>-2.algolianet.com': "AttributeError: module 'aiohttp' has no attribute 'Timeout'", '<APP_ID>-1.algolianet.com': 'ClientConnectionError: Connector is closed.', '<APP_ID>-3.algolianet.com': 'ClientConnectionError: Connector is closed.'})
```

"Unreachable host" would seem to indicate that the client can't connect to my index, but I have double checked the credentials and they do work fine with a synchronous client. Looking at [line 107](https://github.com/algolia/algoliasearch-client-python-async/blob/ffa4b62257bc1fe66bf714938a51c05990ec70a0/algoliasearchasync/transport.py#L107) of transport.py it seems that reaching the host is not actually the problem, but rather the integration of the aiohttp module. Could it be that this is related to Python 3.6? Is there a quick way to fix this?

My complete stack trace is this:

```
Unclosed connection
client_connection: Connection<ConnectionKey(host='<APP_ID>-2.algolianet.com', port=443, ssl=True)>
Traceback (most recent call last):
  File "algolia_async.py", line 19, in <module>
    complete = loop.run_until_complete(main(terms))
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "algolia_async.py", line 13, in main
    return await asyncio.gather(*searches)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/coroutines.py", line 215, in coro
    res = yield from res
  File "<PROJECT_PATH>/venv/lib/python3.6/site-packages/algoliasearchasync/transport.py", line 107, in req
    raise AlgoliaException('Unreachable hosts: %s', exceptions)
algoliasearch.helpers.AlgoliaException: ('Unreachable hosts: %s', {'<APP_ID>-dsn.algolia.net': "AttributeError: module 'aiohttp' has no attribute 'Timeout'", '<APP_ID>-2.algolianet.com': "AttributeError: module 'aiohttp' has no attribute 'Timeout'", '<APP_ID>-1.algolianet.com': 'ClientConnectionError: Connector is closed.', '<APP_ID>-3.algolianet.com': 'ClientConnectionError: Connector is closed.'})
```

### PR DESCRIPTION
**Pull request by gmolau**
aiohttp has no attribute `Timeout` and this context manager wasn't used
anyway.

Fixes #6

### CODE REVIEW

**Comment by gmolau** [comment]
Note that the tests fail because the test suite doesn't have a `ALGOLIA_APPLICATION_ID ` environment variable. Providing one in a local environment fails with an `SSL: CERTIFICATE_VERIFY_FAILED` error. I'm not sure where this is coming from, but it's most likely not related to the fix proposed here, without which the library doesn't work at all.

**Comment by julienbourdeau** [comment]
Thanks a lot for your contribution. Looking at the issue and the change made this seems correct but I need to have a deeper look.

About the tests, yes it's expected to fail as I didn't rollout [our solution to manage Travis encrypted vars](https://blog.algolia.com/travis-encrypted-variables-external-contributions/) yet but it's coming: https://github.com/algolia/algoliasearch-client-python-async/pull/9

**Comment by LeoErcolanelli** [comment]
@gmolau What do you think of this one instead? Just to keep the timeout guard: https://github.com/algolia/algoliasearch-client-python-async/pull/10

**Comment by gmolau** [comment]
Closing this because #10 is a better solution.

**Pull request closed without merging**
