### PR TITLE
Include a proper requirements.txt file

### PR DESCRIPTION
**Pull request by gmolau**
Include `pip freeze` output as requirements file. Adds `Faker`, which is used in unittests.

### CODE REVIEW

**Comment by gmolau** [comment]
See #8 for an explanation of the test failure.

**Comment by julienbourdeau** [comment]
Thanks for your contribution.

Faker should definitely be in the `requirements.txt` 👍 
About using pip freeze, I'm not sure. Some of the requirements added are not directly used by the lib but is a dependency of a dependency. I believe the version required should be in their `requirements.txt`, not in ours.

What do you think?

**Comment by gmolau** [comment]
Ok, I just saw this requirements file and thought I couldn't do a `pip install -r requirements.txt` with that. Turns out I can. Close this PR if you want.

**Comment by julienbourdeau** [comment]
I will add Faker tho 👍

**Pull request closed without merging**
